
resources:
- alias: usage_report
  format: string
- alias: engine_report
  format: string
- alias: device_info
  format: string
- alias: engine_fetch
  format: string
- alias: fetch_status
  format: string
- alias: update_interval
  format: string
- alias: sensors_report
  format: string
- alias: temperature
  format: float
- alias: humidity
  format: float
- alias: ambient_temperature
  format: float
- alias: desired_temperature
  format: float
- alias: heat_on
  format: integer
  initial: 1
- alias: ac_on
  format: integer
  initial: 0
- alias: change
  format: integer
